### ISSUE TITLE
Laceration on right face

### ISSUE THREAD

**Issue by dustin-wright-bbn** [NextCenturyCorporation/itm-scenario-validator#40]
Running validator on the attached YAML, I get
> Error (yamlValidator):   Key 'location' must have one of the following values ['left face', 'left forearm', 'right forearm', 'left stomach', 'left thigh', 'right thigh', 'left calf', 'right calf', 'left hand', 'right hand'] because 'scenes[8].state.characters[1].injuries[2].name' is 'Laceration', but instead value is 'right face'

It is surprising that "left face" is allowed by "right face" isn't.  I am guessing the intended behavior is "right face" should be allowed or "left face" shouldn't.  But it definitely could be possible that this is correct behavior for reasons I am not seeing.
(Looking at the error message, there might be some other asymmetries, like right stomach?)

Seen on SHA-1: ba02f7769753f33e2c0a7fc0797 (itm-528-final-dre-updates)

---

[example.yaml.txt](https://github.com/user-attachments/files/16394518/example.yaml.txt)

---
I think I have workarounds available, so not high priority.

**Comment by nextcen-dgemoets** [comment]
The simulator only implements lacerations on the left side of the face.  If you need it on the right side of the face (or need them on both sides), we will estimate LOE to add that to the sim.

**Comment by dustin-wright-bbn** [comment]
OK I'll switch to Abrasion, thanks for the quick response.

**Comment by dustin-wright-bbn** [comment]
OK I'll switch to Abrasion, thanks for the quick response.
